name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - Jazper.Website/**

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/jazper-website:latest
    steps:
    - uses: actions/checkout@v5

    - name: Login to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker image
      run: docker build -t $IMAGE_NAME .

    - name: Push Docker image
      run: docker push $IMAGE_NAME
